version: '3.9'

services:
  client:
    build:
      context: .
    volumes:
      - type: bind
        source: .
        target: /usr/src/neatral
      - neatral-node_modules:/usr/src/neatral/node_modules
    ports:
      - "4200:4200"
    tty: true

volumes:
  neatral-node_modules:
    name: neatral-node_modules